# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43ecd575e1fefe35d829f8621ebe06686aa979fc9378e6fc7a7fad28c163c66414f43a517ca043c90d827ffb5d3d8e46d625f19c6bd428da31176d064717619f

test:
  secret_key_base: 2a377f12af04a5fa50a8d4c5b397f1a9da81d009eca1b2824c347fc0a2f7222311ce0a028b1d8bc253c09f8a26381b91c68846b3c94221883092489659f43c37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
